blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', single_view, name='single')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [

    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('test',test_view, name='test'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    # tags=
    category = models.ManyToManyField(Category)
    counted_view = models.IntegerField(default=0)
    status = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

website/models.py
from django.db import models


# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject=models.CharField(max_length=255)
    message=models.TextField()
    created_datetime= models.DateTimeField(auto_now_add=True)
    updated_datetime= models.DateTimeField(auto_now=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post
from datetime import datetime


# Create your views here.
def blog_view(requst):
    posts = Post.objects.filter(status=1, published_date__lte=datetime.now()).order_by('-published_date')
    context = {"posts": posts}
    return render(requst, "blog/blog.html", context)


def single_view(requst, pid):
    post = get_object_or_404(Post, pk=pid, status=True, published_date__lte=datetime.now())
    previous_post = Post.objects.filter(status=True, published_date__lte=datetime.now(),
                                        published_date__lt=post.published_date).order_by('-published_date').first()
    next_post = Post.objects.filter(status=True, published_date__lte=datetime.now(),
                                    published_date__gt=post.published_date).order_by('-published_date').first()
    context = {"post": post, 'previous_post': previous_post, 'next_post': next_post}
    post.counted_view += 1
    post.save()
    return render(requst, "blog/single-blog.html", context)

website/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def index_view(request):
    return render(request, "website/index.html")


def about_view(requst):
    return render(requst, "website/about.html")


def contact_view(requst):
    return render(requst, "website/contact.html")


def test_view(requst):
    context={'title': 'salam', 'content': '://'}
    return render(requst, "website/test.html",context)

templates/base.html
{% load static %}


<html lang="fa">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
        <title>قالب رایگان MeetMe :: فارسی و راست چین شده توسط وب روبیک</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap-rtl.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/popup/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/flaticon/flaticon.css' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    </head>
    <body>

        <!--================Header Menu Area =================-->
        <header class="header_area">
            <div class="main_menu">
            	<nav class="navbar navbar-expand-lg navbar-light">
					<div class="container box_1620">
						<!-- Brand and toggle get grouped for better mobile display -->
						<b><a class="navbar-brand " href="{% url 'website:index' %}" style="color: white;">آشناشو</a></b>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse offset" id="navbarSupportedContent" >
							<ul class="nav navbar-nav menu_nav mr-auto"  >
								<li class="nav-item active"><a class="nav-link" href="{% url 'website:index' %}">خانه</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'website:about' %}">درباره ما</a></li>

								<li class="nav-item submenu dropdown">

									<ul class="dropdown-menu" >

									</ul>
								</li>
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="margin-left:30px;" >وبلاگ</a>
									<ul class="dropdown-menu "  >
										<li class="nav-item"><a class="nav-link txt-alg-hd" href="{% url 'blog:index' %}" >وبلاگ</a></li>

									</ul>
								</li>
								<li class="nav-item"><a class="nav-link" href="{% url 'website:contact' %}"  >تماس با ما</a></li>
							</ul>
						</div>
					</div>
            	</nav>
            </div>
        </header>
        <!--================Header Menu Area =================-->


{% block content %}

{% endblock %}

    <footer class="footer_area p_120">
        	<div class="container">
        		<div class="row footer_inner">
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget ab_widget">
        					<div class="f_title">
        						<h3>درباره ما</h3>
        					</div>
        					<p>آیا میخواهید موفق تر باشید؟ یاد بگیرید که یادگرفتن را دوست داشته باشید و رشد کنید ما برایتان پیشنهاد هایی ارایه میدهیم که توانایی های خود را بیشتر کنید.</p>
        					<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
<p> فارسی و راست چین شده توسط <a href="https://webrubik.com/" target="_blank">وب روبیک </a> علیرضا طرق</p>
        				</aside>
        			</div>
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget news_widget">
        					<div class="f_title">
        						<h3>خبرنامه</h3>
        					</div>
        					<p>با آخرین فعالیت های ما بروز باشید</p>
        					<div id="mc_embed_signup">
                                <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                                	<div class="input-group d-flex flex-row"  >
                                        <input style="text-align: right!important;" name="EMAIL" placeholder="ایمیل خود را وارد نمایید" onfocus="this.placeholder = ''" onblur="this.placeholder = 'آدرس ایمیل '" required="" type="email">
                                        <button class="btn sub-btn" dir="ltr" ><span class="lnr lnr-arrow-left"></span></button>
                                    </div>
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
        				</aside>
        			</div>
        			<div class="col-lg-2">
        				<aside class="f_widget social_widget">
        					<div class="f_title">
        						<h3>ما را دنبال کنید</h3>
        					</div>
        					<p>شبکه های اجتماعی</p>
        					<ul class="list" dir="ltr" >
        						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
        						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
        						<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
        						<li style="margin-right: 10px!important;"><a href="#"><i class="fa fa-behance"></i></a></li>
        					</ul>
        				</aside>
        			</div>
        		</div>
        	</div>
        </footer>
        <!--================End Footer Area =================-->






        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js' %}, then Bootstrap JS -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/stellar.js' %}"></script>
        <script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
        <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'vendors/popup/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'vendors/counter-up/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'vendors/counter-up/jquery.counterup.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/theme.js' %}"></script>
    </body>
</html>

templates/blog/blog-latest-post.html
{% load blog_tags %}
<aside class="single_sidebar_widget popular_post_widget">
    <h3 class="widget_title">پست های محبوب</h3>
    {% for post in posts %}
    <div class="media post_item">
        <img src="{{post.image.url}}" style="width: 100px;height: auto;" alt="post">
        <div class="media-body">
            <a href="{% url 'blog:single' pid=post.id %}"><h3>{{post.title}}</h3></a>
            <p>{{post.published_date}}</p>
        </div>
    </div>
    {% endfor %}
    <div class="br"></div>
</aside>

templates/blog/blog-writer.html
{% load static %}
<aside class="single_sidebar_widget author_widget">
    <img class="author_img rounded-circle" src="{% static 'img//blog/author.png' %}" alt="">
    <h4>نوید خان احمدی</h4>
    <p>وبلاگ نویس</p>
    <div class="social_icon">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>
        <a href="#"><i class="fa fa-behance"></i></a>
    </div>
    <p>وبلاگ نویسی به نوعی احترام به بازدید کننده و مخاطب است و شرایطی به وجود می‌آورد که آنها راحت‌تر به اطلاعات مورد
        نیاز دسترسی داشته باشند.</p>
    <div class="br"></div>
</aside>

templates/website/about.html
 {% extends 'base.html' %}
{% load static %}

{% block content %}

        
       <!--================Home Banner Area =================-->
        <section class="home_banner_area">
           	<div class="container box_1620">
           		<div class="banner_inner d-flex align-items-center">
					<div class="banner_content">
						<div class="media" >
							<div class="d-flex" style="padding-right: 0px!important;" >
								<img src="{% static 'img/navid.jpg.jpg' %}" alt="" style="width: 700px; height: 700px;">
							</div>
							<div class="media-body" >
								<div class="personal_text txt_al_ps" >
									<h6>سلام دوستان عزیز </h6>
									<h3>نوید احمدی </h3>
									<h4>طراح صفحات وب روبیک هستم </h4>
									<p>اینجا هستم که به شما نحوه طراحی وب با زبان های برنامه نویسی محبوب و جدید که طراحان وب با آن ها کار میکنند را یاد دهم </p>
									<ul class="list basic_info" style="text-align: right;" >
										<li> <a href="#"><i class="lnr lnr-calendar-full"  ></i><span class="spn_ic">26 خرداد 1378</span></a></li>
										<li><a href="#"><i class="lnr lnr-phone-handset"></i><span class="spn_ic"> 09117016780</span></a></li>
										<li><a href="#"><i class="lnr lnr-envelope"></i> <span class="spn_ic">n.ahmadi.livani@gmail.com</span></a></li>
										<li><a href="#"><i class="lnr lnr-home"></i><span class="spn_ic">گلستان,گرگان,ویلاشهر</span></a></li>
									</ul>
									<ul class="list personal_social">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->



        <!--================Home Banner Area =================-->
        <section class="profile_area">
           	<div class="container">
           		<div class="profile_inner p_120">
					<div class="row">
						<div class="col-lg-5">
							<img class="img-fluid" src="{% static 'img/IMG_0690.jpg' %}" alt="" style="width: 500px; height: 500px;">
						</div>
						<div class="col-lg-7">
							<div class="personal_text">
								<h6>سلام دوستان </h6>
								<h3>نوید احمدی</h3>
								<h4>طراح صفحات وب روبیک هستم </h4>
								<p>اینجا هستم که به شما نحوه طراحی وب با زبان های برنامه نویسی محبوب و جدید که طراحان وب با آن ها کار میکنند را یاد دهم </p>
								<ul class="list basic_info" style="text-align: right;" >
									<li> <a href="#"><i class="lnr lnr-calendar-full"  ></i><span class="spn_ic">26 خرداد1378</span></a></li>
									<li><a href="#"><i class="lnr lnr-phone-handset"></i><span class="spn_ic"> 09117016780</span></a></li>
									<li><a href="#"><i class="lnr lnr-envelope"></i> <span class="spn_ic">n.ahmadi.livani@gmail.com</span></a></li>
									<li><a href="#"><i class="lnr lnr-home"></i><span class="spn_ic">گلستان,گرگان,ویلاشهر </span></a></li>
								</ul>
								<ul class="list personal_social">
									<li><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
           		</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->


		<!--================Testimonials Area =================-->
		<section class="testimonials_area p_120">
			<div class="container">
				<div class="main_title">
					<h2>رضایت کاربران</h2>
					<p>شما میتوانید در این قسمت ایده ها و نظرات کسانی را که با سایت ما آشنا شده اند را بخوانید و شما نیز نظرات خود را درباره ی موفقیت های خود بگذارید</p>
				</div>
				<div class="testi_inner">
					<div class="testi_slider owl-carousel">
						<div class="item">
							<div class="testi_item" dir="rtl">
								<p>با وجود شما من تونستم بر روی محتوا گذاشتن روی وبسایتم به خوبی متمرکز بشم و خیالم از مسائل فنی راحت شده. خیلی خوشحالم که بخش فنی سایتم رو به دست فردی با تجربه و قابل اعتماد سپردم.</p>
								<h4>امیر زارعیان</h4>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star-half-o flip_H" ></i></a>
							</div>
						</div>
						<div class="item">
							<div class="testi_item" dir="rtl">
								<p>این سایت و خدماتش واقعا عالی هستن و حس خیلی خوبیه وقتی ببینی هرمشکلی که سایتت داشته باشه مهم نیست چون شخصی هست که میتونه براحتی بهتون راه حل بده.</p>
								<h4>علیرضا حسینی</h4>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star-half-o flip_H"></i></a>
							</div>
						</div>
						<div class="item">
							<div class="testi_item" dir="rtl">
								<p>از این بابت خیلی خوشحالم که میتونم برای هر مشکلی که داشتم بلافاصله از شما کمک بگیرم و شما بلافاصله در هر ساعت از شبانه روز که باشه آنلاین پاسخگو هستید.</p>
								<h4>مصطفی سلیمی </h4>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star"></i></a>
								<a href="#"><i class="fa fa-star-half-o flip_H"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--================End Testimonials Area =================-->
        
 {% endblock %}

templates/website/contact.html
 {% extends 'base.html' %}
{% load static %}

{% block content %}

        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="box_1620">
				<div class="banner_inner d-flex align-items-center">
					<div class="container">
						<div class="banner_content text-center">
							<h2>تماس با ما</h2>
							<div class="page_link">
								<a href="index.html">خانه</a>
								<a href="contact.html">تماس با ما</a>
							</div>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Contact Area =================-->
        <section class="contact_area p_120">
            <div class="container">
                <div id="mapBox" class="mapBox" 
                    data-lat="40.701083" 
                    data-lon="-74.1522848" 
                    data-zoom="13" 
                    data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia."
                    data-mlat="40.701083"
                    data-mlon="-74.1522848">
                </div>
                <div class="row">
                    <div class="col-lg-3">
                        <div class="contact_info">
                            <div class="info_item">
                                <i class="lnr lnr-home"></i>
                                <h6>ایران ، استان فارس</h6>
                                <p>شیراز ، بلوار جمهوری</p>
                            </div>
                            <div class="info_item">
                                <i class="lnr lnr-phone-handset"></i>
                                <h6><a href="#">۰۷۱۳۲۳۰۹۵۳۴</a></h6>
                                <p>شنبه تا پنجشنبه ساعت ۹  تا ۱۴</p>
                            </div>
                            <div class="info_item">
                                <i class="lnr lnr-envelope"></i>
                                <h6><a href="#">info@webrubik.ir</a></h6>
                                <p>نظرات خود را برای ما ارسال کنید</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <form class="row contact_form" action="contact_process.php" method="post" id="contactForm" novalidate="novalidate">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="name" name="name" placeholder="نام خود را وادر کنید">
                                </div>
                                <div class="form-group">
                                    <input style="text-align: right;" type="email" class="form-control" id="email" name="email" placeholder="آدرس ایمیل خود را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" id="subject" name="subject" placeholder="موضوع را وارد کنید">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <textarea class="form-control" name="message" id="message" rows="1" placeholder="نظر خد را وارد کنید"></textarea>
                                </div>
                            </div>
                            <div class="col-md-12 text-right">
                                <button type="submit" value="submit" class="btn submit_btn" style="float: left;" >ارسال دیدگاه</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!--================Contact Area =================-->
         <!-- contact js -->
        <script src="js/jquery.form.js"></script>
        <script src="js/jquery.validate.min.js"></script>
        <script src="js/contact.js"></script>
        <!--gmaps Js-->
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
        <script src="js/gmaps.min.js"></script>
        <script src="js/theme.js"></script>
 {% endblock %}
        

templates/website/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<P>
    {{title}}
    {{content}}
</P>
</body>
</html>